GET http://localhost:3000/users

###

POST http://localhost:3000/createUser
Content-Type: application/json

{
    "username": "snuttsson2234",
    "pwd": "123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "snuttsson2234",
    "pwd": "123"
}

###

DELETE http://localhost:3000/logout

###

GET http://localhost:3000/products

###

POST http://localhost:3000/createProduct
Content-Type: application/json

{
    "productName": "test",
    "productDescription": "Res iväg till italien2",
    "productPrice": 1337,
    "imageSrc": "lorempixum.png"
}

###

PUT http://localhost:3000/updateProduct
Content-Type: application/json

{
    "productName": "Resa till Italien3",
    "productDescription": "Res iväg till italien3",
    "productPrice": 1337,
    "imageSrc": "lorempixum.png",
    "Id": 3
}

###

DELETE http://localhost:3000/deleteProduct
Content-Type: application/json

{
    "Id": 3
}

###

POST http://localhost:3000/upload
Content-Type: application/json

{
    "imageSrc": "blabla.png"
}

###

GET http://localhost:3000/orders
###

GET http://localhost:3000/live
