GET http://localhost:3000/users

###

POST http://localhost:3000/createUser
Content-Type: application/json

{
    "username": "hej",
    "pwd": "hej"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "hej",
    "pwd": "hej"
}

###

DELETE http://localhost:3000/logout

###

GET http://localhost:3000/products

###

POST http://localhost:3000/createProduct
Content-Type: application/json

{
    "productName": "test",
    "productDescription": "test",
    "productPrice": 1337,
    "imageSrc": "lorempixum.png"
}

###

PUT http://localhost:3000/updateProduct
Content-Type: application/json

{
    "productName": "test",
    "productDescription": "test",
    "productPrice": 1337,
    "imageSrc": "lorempixum.png",
    "productId": "c9d4c016-b85b-405c-b496-68c0262837cd"
}

###

DELETE http://localhost:3000/deleteProduct
Content-Type: application/json

{
    "id": "3665eca5-6afb-445a-9dff-0afeca2ddbdc"
}

###

POST http://localhost:3000/upload
Content-Type: application/json

{
    "imageSrc": "blabla.png"
}

###

GET http://localhost:3000/orders
###

GET http://localhost:3000/live
